### ISSUE TITLE
CSharp example has issue

### ISSUE THREAD

**Issue by cannjeff** [amzn/amazon-pay-sdk-samples#11]
The AddressBook and Wallet widgets fail to load in the C# OneTimePayments example. They both display "We're sorry, but there's a problem processing your payment from this website. Please contact the seller for assistance." And the error message returned in the onError handlers is "InvalidOrderReferenceId The OrderReferenceID S01-5932202-9814938 is invalid."

All app settings appear correct and all dependencies are installed. Any ideas why this example code doesn't work?

**Comment by islandskater43** [comment]
Hey @cannjeff, is there any chance you have sample code that we can see so that we can troubleshoot?
