### ISSUE TITLE
Python: incorrect `redirect_url`?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [amzn/amazon-pay-sdk-samples#14]
This one.

https://api-cdn.amazon.com/sdk/2017-06-26-ffwvf3yd/topic.html?uri=http%3A%2F%2F127.0.0.1%3A5000%2Fcart&proxy=amazon-proxy-https-api_cdn_amazon_com&topic=UReWwsIv2up8qBz7&version=1

I whitelisted this address but I get the same http status code 400.

**Comment by bjguillot** [comment]
The URL of http://127.0.0.1 would need to be whitelisted in "Allowed JavaScript Origins" in that specific case.  If you're using the redirect flow, then http://127.0.0.1:5000/cart would need to be listed in "Allowed Return URLs" for your specific case.

If you are still encountering issues, please submit a support case using the following link:
https://sellercentral.amazon.com/gp/contact-us/contact-amazon-form.html

Be sure to select "Amazon Pay" and then "Technical Troubleshooting" to ensure your question is routed to the correct support queue.
