### ISSUE TITLE
Button and other widgets for React

### ISSUE THREAD

**Issue by slava-lu** [amzn/amazon-pay-sdk-samples#18]
Hi Amazon dev team.  
Do you have any React library to add button, address book and wallet widgets in declarative React.js style rather then binding them to some exiting element ids? 
PayPal has this functionality:)

**Comment by ladas-larry** [comment]
Something like Stripe has would be awesome https://github.com/stripe/react-stripe-elements#example

**Comment by bjguillot** [comment]
We only support binding at this time, but thanks for the suggestion.  I've passed it along to our development team for consideration.

**Comment by skepticshivam** [comment]
Do we have a SDK for react-native?
