### ISSUE TITLE
Login with Amazon callback/event if popup is closed

### ISSUE THREAD

**Issue by timmixell** [amzn/amazon-pay-sdk-samples#22]
I'm nearly finished wiring Amazon Pay without the Address Book widget: https://pay.amazon.com/us/developer/documentation/lpwa/201953690

I am using the sandbox js.

Is there any kind of callback or event I can listen on if the end user closes the login popup? I thought maybe the `next` argument of `authorize` might do what I need, but it doesn't appear to be getting anything.

Barring that, what's the best practice for this scenario, and is it documented anywhere?

Thanks!

**Comment by bjguillot** [comment]
timmixell: Unfortunately, there isn't an event that fires if the user just closes the login popup.  You can try the redirect flow instead, as biplobice mentioned.  It's a bit more complicated to do that, but it may help with your use case depending upon what end result you are are trying to get.

If you want to discuss this in more depth, feel free to submit a support case using the following link:
https://sellercentral.amazon.com/gp/contact-us/contact-amazon-form.html

Be sure to select "Amazon Pay" and then "Technical Troubleshooting" to ensure your question is routed to the correct support queue.

**Comment by carlows** [comment]
Is this event being planned at all? How would we even know if the user closed the popup?
