### ISSUE TITLE
Wallet Widget error: InvalidOrderReferenceId - The OrderReferenceID  is invalid.

### ISSUE THREAD

**Issue by jahanzaibkhanrana** [amzn/amazon-pay-sdk-samples#23]
What I did is just change the setOrderReferenceDetails request parameter "amount", 1st it warned me that you can not change the payment method in open or cancelled state but when i cancelled the transaction from my seller account then, it is not allowing to proceed from my web and not rendering Wallet widget

![image](https://user-images.githubusercontent.com/11090008/55706667-33122000-59fb-11e9-8f0d-1b2b0c7f9b0c.png)

**Comment by bjguillot** [comment]
Please create a case for our developer support team so that we can take a closer look at your implementation and assist.

https://sellercentral.amazon.com/gp/contact-us/contact-amazon-form.html

Then Select "Amazon Pay" -> Technical troubleshooting
