### ISSUE TITLE
Amazon Pay Strong Customer Authentication (SCA) Upgrade

### ISSUE THREAD

**Issue by samuelyuri** [amzn/amazon-pay-sdk-samples#24]
Hello,
Is there any plans to add the SCA to the examples?
https://s3.amazonaws.com/amazonpayments/documents/Amazon_Pay_SCA_Upgrade_integration_guide_2019.pdf

Thank you in advance.

**Comment by bjguillot** [comment]
There are some additional explanations and code snippets posted here:
https://developer.amazon.com/docs/eu/amazon-pay-onetime/sca-upgrade.html

You have a good suggestion to create some stand-alone samples to supplement the integration guide and developer documentation.

In case others are watching: Please note the SCA code snippets only apply to the EU and UK Amazon Pay regions.  (They do not apply for US and JP regions.)

**Comment by samuelyuri** [comment]
Right, as soon as I finish the update and overcoming the issue that I am dealing with now, I can create it.

**Comment by adrianiftode** [comment]
@samuelyuri possible to do a PR here? or some hints?

**Comment by samuelyuri** [comment]
Hi @adrianiftode 

Regarding hints that I can give based on the experience that I had:

- Make sure you are using the European Widget instead of North American because SCA is only for Europe.
- All the examples without SCA have the Authorize call after the confirmation call, you need to change that, the authorise call takes place in your callback(the Success call) that you inform to Amazon.
- If you have only a form submit, needs to change to an AJAX call and add the "_confirmationFlow_" described in the docs.
- The Failure URL was optional in the previous documentation, then I didn't add any handling in this example, but it's good that is required now, it improves the quality of the service from my point of view.
- This [doc](https://m.media-amazon.com/images/G/03/AmazonPay/integration/flowcharts/AP-Integration-Flow_-_Checkout_-_Decline-Handling_sync-only__PSD2-Ready._CB1198675309_.pdf) describes the full process to handle all the scenarios (Challenge Failed, Unauthorized, Invalid Payment, Timeout, etc.), so you need to implement this as well to bring it live.

Regarding the PR:
I committed an example in the Python examples(based on one of the implementations), I need to add a call to the Failure URL, and then I can open a PR at least as an example of the SCA, but as I said there are [changes in the process](https://m.media-amazon.com/images/G/03/AmazonPay/integration/flowcharts/AP-Integration-Flow_-_Checkout_-_Decline-Handling_sync-only__PSD2-Ready._CB1198675309_.pdf), and this is not covered in this example

**Comment by adrianiftode** [comment]
Thanks @samuelyuri . Regarding the doc, the text is not selectable, so for example if I want to follow a link or want to copy a suggested error message, then I am not able to do this.

**Comment by samuelyuri** [comment]
Hi @bjguillot 
Is it possible to change this on that PDF?

**Comment by bjguillot** [comment]
@samuelyuri can you clarify what you are asking for regarding changes to the PDF?  The most current documentation is on the web at:

https://developer.amazon.com/docs/eu/amazon-pay-onetime/sca-upgrade.html

**Comment by samuelyuri** [comment]
@bjguillot the last comment from @adrianiftode [here](https://github.com/amzn/amazon-pay-sdk-samples/issues/24#issuecomment-511429102) about the 
PDF(the one at https://developer.amazon.com/docs/eu/amazon-pay-onetime/sca-upgrade.html showing the flow)

**Comment by doctordebug** [comment]
Hi @samuelyuri ,

we added a SVG version of the flowchart to https://developer.amazon.com/docs/eu/amazon-pay-onetime/sca-upgrade.html.
There you can copy and paste the links. You can find our recommended error messages @ [this section](https://developer.amazon.com/docs/eu/amazon-pay-onetime/sca-upgrade.html#recommended-errors-messages ) section of the same page.
