### ISSUE TITLE
Can not callback when clicked the consent widgets ( throw error 400 bad request ) in PHP example recurring payment

### ISSUE THREAD

**Issue by hapo-tuanbv** [amzn/amazon-pay-sdk-samples#27]
![Screen Shot 2019-07-24 at 4 27 34 PM](https://user-images.githubusercontent.com/47956923/61782282-fc3c0a80-ae2f-11e9-8de7-d804107ab66b.png)

**Comment by hapo-tuanbv** [comment]
![Screen Shot 2019-07-24 at 4 54 58 PM](https://user-images.githubusercontent.com/47956923/61784397-d3b60f80-ae33-11e9-8e85-9edc684871a7.png)

**Comment by hapo-tuanbv** [comment]
![Screen Shot 2019-07-24 at 5 54 14 PM](https://user-images.githubusercontent.com/47956923/61788361-20054d80-ae3c-11e9-8171-2f3f3d75f203.png)
![Screen Shot 2019-07-24 at 5 54 03 PM](https://user-images.githubusercontent.com/47956923/61788383-272c5b80-ae3c-11e9-8a9b-706b3d67a2ad.png)

**Comment by bjguillot** [comment]
Thanks for bringing this to our attention.  We're looking into it now.  In the meantime, can you let us know what web browser, version, and OS you are using?

**Comment by hapo-tuanbv** [comment]
I’m using web browser is google chrome 77 on macOS Mojave (10.14.5), some
picture about this error in a network when I clicked the consent widgets.
Hope that will give you enough information to help me out!

**Comment by hapo-tuanbv** [comment]
I have just used that demo in new incognito window on Chrome and it works, but I do not know the reason, please explain this for me :worried:

**Comment by hapo-tuanbv** [comment]
@bjguillot Are you there?

**Comment by bjguillot** [comment]
If it is working in a incognito window but not the normal window, it's possible there could be something set incorrectly in your cookies.  Try clearing your cookies and cache, restart the browser, and see if the problem still occurs.

**Comment by hapo-tuanbv** [comment]
Thank for your support!
